// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfvvtjI40_X13EtcKfGGmRUl9v06Oe8Y',
    appId: '1:947911277694:web:184dfe57e4774f5795ec2f',
    messagingSenderId: '947911277694',
    projectId: 'chat-b08b5',
    authDomain: 'chat-b08b5.firebaseapp.com',
    storageBucket: 'chat-b08b5.appspot.com',
    measurementId: 'G-H7WDKRD37Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTMPs2cJzsycClktiaOzjkdSY4XrAvD0',
    appId: '1:947911277694:android:f4ae12dd0c323a5195ec2f',
    messagingSenderId: '947911277694',
    projectId: 'chat-b08b5',
    storageBucket: 'chat-b08b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKm1oGMrnbHsaejOU9r3lqSu63wunFhHs',
    appId: '1:947911277694:ios:b044a18a3d48eb0095ec2f',
    messagingSenderId: '947911277694',
    projectId: 'chat-b08b5',
    storageBucket: 'chat-b08b5.appspot.com',
    iosClientId: '947911277694-0kjlkickhnbqj07j0oau2soakplt1613.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
